insert into User (email, password) VALUES ('gyula@something.com', '$2a$10$kOIWxlkxbU1NtqSF/Q2r9enhORF4KDogYjqCMCilex9mlF7z0KRne');
insert into User (email, password) VALUES ('csilla@something.com', '$2a$10$X0.amibuDw/3giiohc2bhODu9O2V8JmPNJvJ0xCas.qdDKxguiuK2');
insert into User (email, password) VALUES ('alma@something.com', '$2a$10$X0.amibuDw/3giiohc2bhODu9O2V8JmPNJvJ0xCas.qdDKxguiuK2');
insert into User (email, password) VALUES ('endre@something.com', '$2a$10$X0.amibuDw/3giiohc2bhODu9O2V8JmPNJvJ0xCas.qdDKxguiuK2');
insert into User (email, password) VALUES ('laci@something.com', '$2a$10$X0.amibuDw/3giiohc2bhODu9O2V8JmPNJvJ0xCas.qdDKxguiuK2');
insert into Locker (owner_id) values ((select id FROM USER where email like '%alma%'));
insert into Locker (owner_id) values ((select id FROM USER where email like '%gyula%'));
insert into Locker (owner_id) values ((select id FROM USER where email like '%csilla%'));
insert into Locker (owner_id) values ((select id FROM USER where email like '%laci%'));
insert into Locker (owner_id) values ((select id FROM USER where email like '%endre%'));
insert into Locker (owner_id) values (null);
insert into Locker (owner_id) values (null);
insert into Locker (owner_id) values (null);
insert into Locker (owner_id) values (null);
insert into Locker (owner_id) values (null);